api_platform:
    defaults:
        pagination_client_enabled: true
    title : 'Mon api Discord'
    description : 'Une api pour les données de notre serveur discord'
    formats:
        jsonld:
            mime_types: ['application/ld+json']

        json:
            mime_types: ['application/json']

        html:
            mime_types: ['text/html']
        